# #
# sls deploy
# serverless invoke --function bmi  --data '{ "height": 1.8, "weight": 50}' --log

service: bmi-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1
  memorySize: 128

functions:
  bmi:
    handler: handler.lambda_handler
    events:
      - http:
          path: bmi
          method: post